// src/core/commands/generic/command_cmd.rs

use crate::core::commands::command_spec::CommandSpec;
use crate::core::commands::command_trait::{
    CommandFlags, ExecutableCommand, ParseCommand, WriteOutcome,
};
use crate::core::database::ExecutionContext;
use crate::core::protocol::RespFrame;
use crate::core::{RespValue, SpinelDBError};
use async_trait::async_trait;
use bytes::Bytes;
use once_cell::sync::Lazy;

/// A command for introspecting other commands.
/// Corresponds to the `COMMAND` SpinelDB command.
#[derive(Debug, Clone, Default)]
pub struct CommandInfo;

impl ParseCommand for CommandInfo {
    fn parse(args: &[RespFrame]) -> Result<Self, SpinelDBError> {
        if !args.is_empty() {
            // SpinelDB' COMMAND can take subcommands, but this implementation does not yet.
            // For now, we only support the parameter-less variant.
            return Err(SpinelDBError::WrongArgumentCount("COMMAND".to_string()));
        }
        Ok(CommandInfo)
    }
}

impl CommandSpec for CommandInfo {
    fn name(&self) -> &'static str {
        "command"
    }
    fn arity(&self) -> i64 {
        // Arity is -1 because it can have subcommands, even if not implemented here.
        -1
    }
    fn flags(&self) -> CommandFlags {
        CommandFlags::ADMIN | CommandFlags::NO_PROPAGATE | CommandFlags::READONLY
    }
    fn first_key(&self) -> i64 {
        0
    }
    fn last_key(&self) -> i64 {
        0
    }
    fn step(&self) -> i64 {
        0
    }
    fn get_keys(&self) -> Vec<Bytes> {
        vec![]
    }
    fn to_resp_args(&self) -> Vec<Bytes> {
        vec![]
    }
}

/// Converts `CommandFlags` into a `Vec<RespValue>` of simple strings.
fn flags_to_resp_values(flags: CommandFlags) -> Vec<RespValue> {
    let mut flag_values = Vec::new();
    if flags.contains(CommandFlags::WRITE) {
        flag_values.push(RespValue::SimpleString("write".to_string()));
    }
    if flags.contains(CommandFlags::READONLY) {
        flag_values.push(RespValue::SimpleString("readonly".to_string()));
    }
    if flags.contains(CommandFlags::DENY_OOM) {
        flag_values.push(RespValue::SimpleString("denyoom".to_string()));
    }
    if flags.contains(CommandFlags::ADMIN) {
        flag_values.push(RespValue::SimpleString("admin".to_string()));
    }
    if flags.contains(CommandFlags::PUBSUB) {
        flag_values.push(RespValue::SimpleString("pubsub".to_string()));
    }
    if flags.contains(CommandFlags::NO_PROPAGATE) {
        flag_values.push(RespValue::SimpleString("no_propagate".to_string()));
    }
    if flags.contains(CommandFlags::TRANSACTION) {
        flag_values.push(RespValue::SimpleString("transaction".to_string()));
    }
    if flags.contains(CommandFlags::MOVABLEKEYS) {
        flag_values.push(RespValue::SimpleString("movablekeys".to_string()));
    }
    flag_values
}

/// Builds the detailed RESP response for a single command from its `CommandSpec`.
fn build_command_details_from_spec(spec: &dyn CommandSpec) -> RespValue {
    RespValue::Map(vec![
        (
            RespValue::BulkString("name".into()),
            RespValue::BulkString(spec.name().to_ascii_uppercase().into()),
        ),
        (
            RespValue::BulkString("arity".into()),
            RespValue::Integer(spec.arity()),
        ),
        (
            RespValue::BulkString("flags".into()),
            RespValue::Array(flags_to_resp_values(spec.flags())),
        ),
        (
            RespValue::BulkString("first_key".into()),
            RespValue::Integer(spec.first_key()),
        ),
        (
            RespValue::BulkString("last_key".into()),
            RespValue::Integer(spec.last_key()),
        ),
        (
            RespValue::BulkString("step".into()),
            RespValue::Integer(spec.step()),
        ),
    ])
}

// Lazily build and sort the command specifications once at startup.
static SORTED_COMMAND_SPECS: Lazy<Vec<RespValue>> = Lazy::new(|| {
    // Import the function generated by the `define_commands!` macro.
    use crate::core::commands::get_all_command_specs;
    let specs = get_all_command_specs();
    let mut details: Vec<_> = specs
        .iter()
        .map(|spec| build_command_details_from_spec(spec.as_ref()))
        .collect();

    // Sort the command details alphabetically by name for consistent output.
    details.sort_by(|a, b| {
        if let RespValue::Map(entries_a) = a
            && let RespValue::Map(entries_b) = b
        {
            // Find the "name" entry in each Map
            let name_a = entries_a
                .iter()
                .find(|(k, _)| matches!(k, RespValue::BulkString(bs) if bs.as_ref() == b"name"))
                .map(|(_, v)| v);
            let name_b = entries_b
                .iter()
                .find(|(k, _)| matches!(k, RespValue::BulkString(bs) if bs.as_ref() == b"name"))
                .map(|(_, v)| v);
            if let (Some(RespValue::BulkString(a)), Some(RespValue::BulkString(b))) =
                (name_a, name_b)
            {
                return a.cmp(b);
            }
        }
        std::cmp::Ordering::Equal
    });
    details
});

#[async_trait]
impl ExecutableCommand for CommandInfo {
    async fn execute<'a>(
        &self,
        _ctx: &mut ExecutionContext<'a>,
    ) -> Result<(RespValue, WriteOutcome), SpinelDBError> {
        // Return the pre-built, sorted list of command specifications.
        Ok((
            RespValue::Array(SORTED_COMMAND_SPECS.clone()),
            WriteOutcome::DidNotWrite,
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::commands::command_spec::CommandSpec;
    use crate::core::commands::command_trait::ParseCommand;
    use crate::core::protocol::RespFrame;

    #[test]
    fn test_parse_no_args() {
        let cmd = CommandInfo::parse(&[]).unwrap();
        assert_eq!(cmd.name(), "command");
    }

    #[test]
    fn test_parse_with_args_errors() {
        assert!(CommandInfo::parse(&[RespFrame::BulkString(bytes::Bytes::from("info"))]).is_err());
    }

    #[test]
    fn test_command_arity() {
        assert_eq!(CommandInfo.arity(), -1);
    }

    #[test]
    fn test_command_flags() {
        let flags = CommandInfo.flags();
        assert!(flags.contains(CommandFlags::ADMIN));
        assert!(flags.contains(CommandFlags::NO_PROPAGATE));
        assert!(flags.contains(CommandFlags::READONLY));
    }

    #[test]
    fn test_get_keys_empty() {
        assert!(CommandInfo.get_keys().is_empty());
    }

    #[test]
    fn test_first_last_step() {
        let cmd = CommandInfo;
        assert_eq!(cmd.first_key(), 0);
        assert_eq!(cmd.last_key(), 0);
        assert_eq!(cmd.step(), 0);
    }

    #[test]
    fn test_to_resp_args_empty() {
        assert!(CommandInfo.to_resp_args().is_empty());
    }

    #[test]
    fn test_flags_to_resp_values_write() {
        let vals = flags_to_resp_values(CommandFlags::WRITE);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "write"));
    }

    #[test]
    fn test_flags_to_resp_values_readonly() {
        let vals = flags_to_resp_values(CommandFlags::READONLY);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "readonly"));
    }

    #[test]
    fn test_flags_to_resp_values_admin() {
        let vals = flags_to_resp_values(CommandFlags::ADMIN);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "admin"));
    }

    #[test]
    fn test_flags_to_resp_values_denyoom() {
        let vals = flags_to_resp_values(CommandFlags::DENY_OOM);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "denyoom"));
    }

    #[test]
    fn test_flags_to_resp_values_pubsub() {
        let vals = flags_to_resp_values(CommandFlags::PUBSUB);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "pubsub"));
    }

    #[test]
    fn test_flags_to_resp_values_no_propagate() {
        let vals = flags_to_resp_values(CommandFlags::NO_PROPAGATE);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "no_propagate"));
    }

    #[test]
    fn test_flags_to_resp_values_transaction() {
        let vals = flags_to_resp_values(CommandFlags::TRANSACTION);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "transaction"));
    }

    #[test]
    fn test_flags_to_resp_values_movablekeys() {
        let vals = flags_to_resp_values(CommandFlags::MOVABLEKEYS);
        assert_eq!(vals.len(), 1);
        assert!(matches!(&vals[0], RespValue::SimpleString(s) if s == "movablekeys"));
    }

    #[test]
    fn test_flags_to_resp_values_empty() {
        let vals = flags_to_resp_values(CommandFlags::empty());
        assert!(vals.is_empty());
    }

    #[test]
    fn test_flags_to_resp_values_multiple() {
        let flags = CommandFlags::WRITE | CommandFlags::DENY_OOM;
        let vals = flags_to_resp_values(flags);
        assert_eq!(vals.len(), 2);
    }
}
