version: 2

project_name: spineldb

before:
  hooks:
    - rustup default stable
    - cargo fetch --locked

builds:
  - id: linux-build
    builder: rust
    command: zigbuild
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
    env:
      - CC=zig cc -target {{ .Target }}
      - CXX=zig c++ -target {{ .Target }}
      - CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=zig cc -target x86_64-unknown-linux-gnu
      - CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=zig cc -target aarch64-unknown-linux-gnu

  # Build untuk macOS, menggunakan cargo build standar
  - id: mac-build
    builder: rust
    command: build
    targets:
      - x86_64-apple-darwin
      - aarch64-apple-darwin

archives:
  - formats: [tar.gz, zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

universal_binaries:
  - replace: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "Merge pull request"
      - "Merge branch"

release:
  footer: |
    ---
    Dirilis dengan ❤️ menggunakan [GoReleaser](https://goreleaser.com)
