# ===================================================================
#           Main Configuration File for the SpinelDB Server
# ===================================================================
#
# To enable or change a setting, uncomment the line by removing the '#'
# at the beginning.
#
# If a setting is missing or commented out, SpinelDB will use its
# safe, internal default value.
#

# --- General Server Settings ---

# The IP address the server will listen on.
# Default: "127.0.0.1" (only accepts connections from the local machine).
# Use "0.0.0.0" to listen on all available network interfaces.
host = "127.0.0.1"

# The TCP port to use. The standard SpinelDB port is 6379.
port = 7878

# The level of detail for logging.
# Options: "trace", "debug", "info", "warn", "error".
# Default: "info"
log_level = "debug"


# --- Memory Management ---

# The maximum memory limit SpinelDB is allowed to use.
# When this limit is exceeded, the server will start evicting keys
# based on the selected eviction policy.
#
# Default: 536870912 (i.e., 512MB)
#
# The supported format is very flexible:
# 1. A number (in bytes): maxmemory = 268435456
# 2. A string with units: maxmemory = "1gb", "256mb", "512kb", "2g"
# 3. A percentage string of total system RAM: maxmemory = "80%"
#    (SpinelDB is smart and will detect memory limits from containers if present).
#
# To disable the memory limit (NOT RECOMMENDED in production):
# maxmemory = 0
#
# Example: Set the memory limit to 1 Gigabyte.
maxmemory = "512mb"

# The policy used to evict keys when 'maxmemory' is reached.
#
# Policy Options:
#   noeviction        - (Default) Don't evict anything. Return an error on
#                       write commands if memory is full.
#
#   --- LRU (Least Recently Used) Algorithms ---
#   allkeys-lru       - Evict the least recently used key from ALL keys.
#   volatile-lru      - Evict the least recently used key from keys
#                       that have a TTL (expiration time) set.
#
#   --- LFU (Least Frequently Used) Algorithms ---
#   allkeys-lfu       - Evict the least frequently used key from ALL keys.
#   volatile-lfu      - Evict the least frequently used key from keys
#                       that have a TTL set.
#
#   --- Other Policies ---
#   allkeys-random    - Evict a random key from ALL keys.
#   volatile-random   - Evict a random key from keys with a TTL.
#   volatile-ttl      - Evict the key with the shortest remaining time to live (TTL).
#
# Default: "noeviction"
maxmemory_policy = "allkeys-lru"


# --- Security ---

# The password for client authentication via the AUTH command.
# If not set, the server does not require a password.
# It is highly recommended to enable this in production environments.
# Default: no password (None)
#password = "supersecret"


# --- Persistence ---
# Configures how data is saved to disk. SpinelDB supports both SPLDB (snapshot) and AOF.

[persistence]

# -- SPLDB (SpinelDB Snapshot File) Configuration --
# Saves a complete snapshot of the data at specified intervals.
# Good for backups.
#
# Default: true
spldb_enabled = true

# The location of the SPLDB snapshot file.
# Default: "dump.spldb"
spldb_path = "dump.spldb"

# Automatic SPLDB save rules, format: { seconds = <time>, changes = <count> }
# The server will save if at least 'changes' keys have been modified
# in the last 'seconds'. You can have multiple rules.
# Default: standard SpinelDB rules (see below)
save_rules = [
    { seconds = 900, changes = 1 },     # After 15 minutes, if there's at least 1 change
    { seconds = 300, changes = 10 },    # After 5 minutes, if there are at least 10 changes
    { seconds = 60,  changes = 10000 }, # After 1 minute, if there are at least 10000 changes
]

# -- AOF (Append-Only File) Configuration --
# Logs every write command received by the server. More durable than SPLDB
# but results in a larger file.
#
# Default: false
aof_enabled = true

# The location of the AOF file.
# Default: "spineldb.aof"
aof_path = "spineldb.aof"

# Fsync policy for AOF, controlling how often data is physically written to disk.
# - "always":   Safest, slowest. Fsync after every command.
# - "everysec": A good compromise, fsyncs every second via a background task.
# - "no":       Fastest, least safe. Left up to the OS to decide.
# Default: "everysec"
appendfsync = "everysec"


# --- Replication ---
# Configures the server's role as a 'primary' (master) or 'replica' (slave).

#[replication]
#
# Specify the server's role: "primary" or "replica"
# Default: "primary"
#role = "primary"

# --- Example Configuration for a Replica ---
# To make this server a replica, change the 'role' to "replica"
# and uncomment the settings below.
#
# role = "replica"
#
# # The IP address or hostname of the primary server to replicate from.
# primary_host = "127.0.0.1"
#
# # The port of the primary server.
# primary_port = 6379

# --- TLS Configuration ---
#[tls]
# Enable TLS
#enabled = true

# Path to the public certificate file (PEM format)
#cert_path = "spineldb.crt"

# Path to the private key file (PEM format)
#key_path = "spineldb.key"

# --- Access Control List (ACL) ---
# Manages user authentication and command/key authorization.
# Default: false (ACL is disabled by default)
#[acl]
#enabled = false
